### PR TITLE
feat(templates): improve welcome screen luminance effect

### PR DESCRIPTION
**Pull request by antfu**
Make the logo aware of the luminance effect as well:

Before:

https://user-images.githubusercontent.com/11247099/179776050-3a52dde4-09e8-4769-aac0-2e2f939d2f53.mp4

After:

https://user-images.githubusercontent.com/11247099/179775519-389585c7-49b2-425b-9333-8e5afb82d33f.mp4

- In light mode, the "3" is not very readable when the teal background, I would suggest changing it to black, or at least making it darker in light mode. However, the SVG is merged with the mountain so I can't change it separately. Might need help from who has the source file of the logo.
- To improve the "physics" even further, I would suggest we move the loading bar to the top or bottom of the screen, otherwise it's a bit less natural that the bar does not light up the logo.

/cc @Flosciante @Atinux

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Love it.

**Comment by atinux** [comment]
Thank you @antfu 

The main issue I have is the color contrast here:

Screenshot 2022-08-03 at 12 41 54@2x

Happy for you to try with the loading bar at the top, also something I wanted to explore: https://codepen.io/Chokcoco/pen/dypaobm

Happy for you to give an update? Honestly I am up for any innovation to improve the loading experience 🚀

**Comment by antfu** [comment]
@Atinux Yes I am aware of it but I can't modify it as the "3" is blended with the mountain. Need some help here:

> In light mode, the "3" is not very readable when the teal background, I would suggest changing it to black, or at least making it darker in light mode. However, the SVG is merged with the mountain so I can't change it separately. Might need help from who has the source file of the logo.

---

> I wanted to explore: [codepen.io/Chokcoco/pen/dypaobm](https://codepen.io/Chokcoco/pen/dypaobm)

Do you mean by replacing the loading bar to be like the demo? It looks great and sure I can give it a spin

**Comment by antfu** [comment]
I have tried two styles, in two commits:

## Conic fa1ddce3a1f0918a1e692df0244bcc2c84d4d650

(from https://codepen.io/Chokcoco/pen/dypaobm)

https://user-images.githubusercontent.com/11247099/182845140-8e0a3049-08d8-46d2-aa00-35fb63b5ba16.mp4

## Blurred Progress d2f84f14ab9c45e560d1e8ebbeb427b5b745a3f5

https://user-images.githubusercontent.com/11247099/182845201-c2a8eae8-7c69-4a5c-8dc1-17379716390d.mp4


What do you think?

**Comment by atinux** [comment]
Sorry for the delay of my answer.

I love the Blurred Progress @antfu (damn I wish to have answer before the RC8).

**Review by atinux — APPROVED** [review]

**Comment by atinux** [comment]
Do I need to make a manual release @pi0 ?

**Comment by pi0** [comment]
Released as patch (@nuxt/ui-templates@0.3.2)

**Pull request merged**
