### PR TITLE
redesign welcome page

### PR DESCRIPTION
**Pull request by flozero**
First quick draft of the new welcome page waiting for figma public to make sure colors, spacing and responsive is good

related to #11

### CODE REVIEW

**Comment by flozero** [comment]
Don't know why the deploy preview is failing.

**Comment by pi0** [comment]
Thanks for PR @f3ltron but i think we should first wait for design to be ready, approve it is aligned with needs and then start attempting to implement. Meanwhile, we can keep PR open and also PR welcome to fix contrast issue in _current_ implementation without redesign.

**Comment by flozero** [comment]
> Thanks for PR @f3ltron but i think we should first wait for design to be ready, approve it is aligned with needs and then start attempting to implement. Meanwhile, we can keep PR open and also PR welcome to fix contrast issue in _current_ implementation without redesign.

Sure I was mostly thinking about html structure here until I have the figma link public. It will make it easier to just update spacing etc here. 

Base on the discussion #35 discussion. It will update figma and at the end the page for sure

**Comment by R-mooon** [comment]
Hey guys, 
There it is, i updated it with new logo also 😁 

https://www.figma.com/file/owsYNLXpIqwiYU0ciKTc75/NuxtJS-Design?node-id=2%3A309

**Comment by flozero** [comment]
Awesome can i continue with it @pi0  ?

**Comment by flozero** [comment]
@R-mooon There is missing the dark mode I think. Or maybe its define somewhere to which color is what in dark mode ?

As the groups are not components in figma there is no variants. Also for mobile I just align everything ?

**Comment by pi0** [comment]
Sure welcome page design looks good to go. For texts only we have to match new v3.nuxt.js.org structure (getting started, concepts, docs, community)

Unrelated tasks:
- Don't worry about netlify failing issue will fix in in meanwhile in same branch
- Regarding new SVGs, you can keep inlining them but we need to at some point refactor into assets and add license to each

**Comment by flozero** [comment]
Great will start with this and improvise for mobile .
For dark mode color i can check on other pages. But will probably need to have the infos or create the components in figma

EDIT: for the font figma is using DM Sans

https://fonts.google.com/specimen/DM+Sans

I don't see import of this in the code. Should we stay without @pi0  I guess Yes as it's imported inside projects so the fonts will depend on the project

**Comment by flozero** [comment]
More questions:
- The font-size is 32 for titles. But text is not following the ratio size. Should i update the config to follow the sizing ? (the titles are 32 px but text-3xl is 30
- Same point for some margins paddings.

For now i will get the closer px config from tailwind / windi

**Comment by flozero** [comment]
updated @R-mooon  @pi0 

I used shortcuts. But variant is not working on the project don't know why

**Comment by R-mooon** [comment]
i will design you dark hover effects @f3ltron :)

Sorry for late answer !

**Comment by flozero** [comment]
No problem. Awesome thank you @R-mooon. I have use one already tell me if its enough

**Comment by R-mooon** [comment]
Hey @f3ltron so i designed all darkmode here : 
https://www.figma.com/file/owsYNLXpIqwiYU0ciKTc75/?node-id=2%3A309

Also, DM Sans is part of NuxtJS branding and for design consistency it should be in DM Sans, maybe you can import it directly with font url & not downloaded font so people will not have it in project ?

Also some quick feedbacks about design : 
- Social text on hover in light mode should stay dark
- More x-padding on the two buttons at the bottom (i would say 4px each side)
- Add padding on mobile so cards don't touch window edges
- Also you can remove shadow on cards it's not consistent with nuxtjs.org design pages

By the way really great job, so cool to see this design become alive ! 😁

**Comment by flozero** [comment]
Hello ! Updates are done Some feedbacks: @R-mooon 
- windi is really great ^^
- what do you mean about social text ? I have added the social to follow the design so should be good
- the padding for the button I was following the figma padding (it was already 4px). I added a bit for x-
- added padding on mobile on the container
- Reduced margin bottom on mobile 
- removed shadow
- refacto the css usage. And use the power of windi with child elements

**Comment by flozero** [comment]
@R-mooon  any updates feedbacks?

**Comment by R-mooon** [comment]
Hello sorry i was unable to respond. 
Do you have a deploy preview ?

**Comment by flozero** [comment]
I don't know why the preview are not working properly. @pi0  @danielroe  any ideas?

**Comment by pi0** [comment]
Deploy preview is ready.

Current version:  https://templates.ui.nuxtjs.org/templates/welcome
New version:  https://nuxt-ui-templates-jv1vdr7cd-nuxt-js.vercel.app/templates/welcome/

**Comment by pi0** [comment]
**Personal feedback:**

**Design-wise**, the Previous version looks minimal, sharper, and more native-like. Buttons for social media could be added more minimally as icons-only and adding a "Join us" below them is just unnecessary information (action label could be a tooltip). Also, any reason Shadow, bolding and right line in the second box was removed? 

**Usability-wise**, we are adding some links but they should be directly accessible from docs witch has always latest navigation. Something like the internals is not even suitable for getting started! Remember the goal of this page is to **guide users getting started** with the template and is a one-time thing. From the point component is removed, users should already be able to navigate through docs and find useful links like discord to ask their questions. They cannot come back to this to find other links. (later-on we can probably have a tutorial page with devtools/docs but they are not the same)

image

image

**Comment by flozero** [comment]
I don't have strong opinion here But I can definitely agree with what you saying. I like to have a minimalistic approach. Example of socials can only be a clickable button and should be enough the join us is an extra addition that can be not necessary.

About the old one what I think the new one has a more elegant approach.  And in that case same comment about twitter text.

Maybe we can find a way to reduce the amount of element in the new one. I agree that having only one link for getting started will reduce potential failure if the doc endpoints change. And also adding the started part at the same level.

Having socials in this page is interesting I think. But can be more minimalistic. Also would be good to have more analytics in this page. Like a shorten url for social and docs so we know where the user is coming from and the actual usage of this page.

I am totally fine to rework this page Ping me when you come with a consensus

@Atinux  @pi0  @R-mooon

**Comment by atinux** [comment]
I believe we need to add text under each social part instead of Join us. Question is why should they click on it?

For example:
- Twitter: discover the latest updates and news regarding Nuxt
- GitHub: engage and contribute with the framework
- Discord: ask your questions and help the community in real time

I think we need to clearly define what we want to showcase on that page before designing it :thinking:

**Comment by pi0** [comment]
```
For example:

Twitter: discover the latest updates and news regarding Nuxt
GitHub: engage and contribute with the framework
Discord: ask your questions and help the community in real-time
```

Please consider that users see this page one time with a starter template. I believe such information should be directly accessible from the website nav and we should reserve space for built-in futures like starting with built-in dev tools instead and keep icons minimal.

**Comment by flozero** [comment]
Hey what's the update on it? Should I come with an idea ? Or @R-mooon you are working on something already ?

**Comment by atinux** [comment]
Following on #81, thank you so much for your help and feedback @jsbaguette

**Pull request closed without merging**
