### PR TITLE
fix(templates): avoid using blur in no-animation mode, disable animation in Safari

### LINKED ISSUE #174: New loading screen performs extremely bad
Using Safari 16.1 on MacOS.
CPU Usage is at **up to 250%** while the page is displayed.

https://user-images.githubusercontent.com/10992664/195350670-f4d8b465-f396-4dc6-8322-d01757641bed.mov

### PR DESCRIPTION
**Pull request by antfu**
close #174

- avoid using blur in no-animation mode
- disable animation in Safari by default

### CODE REVIEW

**Comment by danielroe** [comment]
On FF I just get a black screen

**Comment by antfu** [comment]
> On FF I just get a black screen

I have no problem with my FF. What's your setup and version?

**Comment by danielroe** [comment]
Actually I get it on both Chrome and Firefox Developer Edition when visiting [the preview URL](https://nuxt-ui-templates-ci32rungp-nuxt-js.vercel.app/templates/loading).

CleanShot 2022-10-14 at 09 38 08

**Comment by antfu** [comment]
Should be fixed now

**Review by danielroe — APPROVED** [review]

**Comment by pi0** [comment]
Should we rework it for new design? @antfu @Atinux

**Comment by antfu** [comment]
Conflicts resolved.

**Review by atinux — APPROVED** [review]

**Comment by atinux** [comment]
Good for me @pi0 

No idea why the components deployment is failing though

**Pull request merged**
